- name: Install Postgres 9.5
  hosts: all
  tasks:
    - name: install the pgdg rpm from a remote repo
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
    - name: install postgresql server
      yum:
          name: "{{ packages }}"
      vars:
          packages:
          - postgresql95-server
    - name: Create Postgres data directory
      file:
        path: "{{ postgres_data_dir }}"
        state: directory
        owner: postgres
    - name: initialize postgresql cluster
      shell: /usr/pgsql-9.5/bin/initdb
      become: yes
      become_user: postgres
      environment:
        PGDATA: "{{ postgres_data_dir }}"
        PGSETUP_INITDB_OPTIONS: "--data-checksums"
    - name: Modify Postgres 9.5 service to adapt pgdata
      file:
        path: /etc/systemd/system/postgresql-95.service.d
        state: directory
    - name: add systemd override
      template:
        src: templates/override.conf
        dest: /etc/systemd/system/postgresql-95.service.d/override.conf
    - name: enable service Postgres 9.5
      systemd:
        daemon_reload: yes
        name: postgresql-9.5
        enabled: yes
    - name: starting Postgres 9.5
      systemd:
        name: postgresql-9.5
        state: started
